### ISSUE TITLE
[Bug]: Update bug

### ISSUE THREAD

**Issue by minus21grams** [Floorp-Projects/Floorp-Portable#48] opened 2024-10-31 21:05 UTC
### Pre-Submission Checklist

- [X] I have checked the existing/closed issues to ensure this issue has not already been reported.
- [X] I am using the latest version of Floorp Portable.
- [X] I have tried disabling all browser extensions/add-ons to rule out interference from these.
- [X] I have tried clearing the browser cache and cookies.
- [X] I have checked with a new profile and the issue still occurs.
- [X] I have checked that this problem is not occurring in the latest version of non-portable Floorp.
- [X] I have checked that this problem is not occurring in the latest version of Firefox ESR.
- [X] I have provided detailed step-by-step instructions on how to reproduce the issue.
- [ ] I have included relevant screenshots or console outputs.
- [ ] I will implement this by myself and send a pull request.

### Bug Summary

Simply put, Floorp won’t update to version 11.20.0
I tried to circumvent this by manually downloading [floorp-11.20.0-portable-windows-x86_64.zip](https://github.com/Floorp-Projects/Floorp-Portable/releases/download/11.20.0-portable/floorp-11.20.0-portable-windows-x86_64.zip) and extracting its contents to the respective folder overwriting "floorp.exe" and "core".
That seemed to do the trick. Or so I thought. Within seconds, auto-update was triggered, downloaded v11.19.1 essentially _downgrading_ Floorp!
Temporary solution: Manually update, then disable (untick) **Automatically check for updates to Floorp portable**.

### Reproduction Steps

1. Run Floorp Portable v11.19.1 and click "Check for updates" (Nothing happens)
2. Manually update to v11.20.0 - if "Automatically check for updates to Floorp portable" is enabled, the browser will downgrade on next restart.

### Expected Behavior

Update to v11.20.0

### Actual Behavior

Reverts to v11.19.1

### Browser Version

11.19.1

### Operating System (for example: Windows 10 Home, Debian 12, Fedora 40)

Windows 10

**Comment by typeling1578** [comment] 2024-10-31 23:55
Oh, I forgot to update [latest.json](https://github.com/Floorp-Projects/Floorp-Updates/blob/main/browser-portable/latest.json).
It is fixed now. Please try again.

**Closed as completed by typeling1578** 2024-10-31 23:55 UTC

**Comment by uugaabuugaa** [comment] 2024-11-01 12:58
Hi. It seems like Floorp fails to move the `core` folder and `floorp.exe` from `update_tmp` to main directory for some reason. Every time I open up Floorp I get notification about update found and ready to update on next time I open browser only to redownload `update_tmp` again when I open browser the next time.

**Comment by typeling1578** [comment] 2024-11-01 13:06
Hmmm, please run the following command using the command prompt to force Floorp to shut down and try again

```
taskkill /im floorp.exe /F /T
```

**Comment by uugaabuugaa** [comment] 2024-11-01 13:09
Okay but do I need to change directory first? cause I have a another folder with Floorp to test different `user.js` `userChrome.css` stuffs. And do I close Floorp normally beforehand or keep it running while using the command?
Edit: I haven't opened that in a while tho

**Comment by uugaabuugaa** [comment] 2024-11-01 13:18
Okay I ran the command after closing Floorp normally before doing it and it says `ERROR: The process "floorp.exe" not found.` I'm assuming if I run it while Floorp is running I'm going to lose all my tabs?

**Comment by typeling1578** [comment] 2024-11-01 13:26
Apparently there was no remaining Floorp process behind the scenes.
Another possibility is that other software is opening files under the core folder; if write access to the core folder is denied, the portable runtime will not perform the update.

**Comment by uugaabuugaa** [comment] 2024-11-01 13:31
How can I give write access to core folder? Because all editing and stuff I did was limited to profiles directory only. Any changes done there is putting the `floorp-portable-default.bat` in the main folder to make it default browser app and that's it.

**Comment by typeling1578** [comment] 2024-11-01 13:35
Does floorp-portable-default.bat set floorp.exe in the root directory or floorp.exe in the core folder as the default browser?

**Comment by typeling1578** [comment] 2024-11-01 13:58
Perhaps write access need not be explicitly given.

**Comment by uugaabuugaa** [comment] 2024-11-01 13:59
> Does floorp-portable-default.bat set floorp.exe in the root directory or floorp.exe in the core folder as the default browser?

The one in root directory. 

Okay an interesting thing happened. I just saw the core properties attributes and it was set to read only. So I unchecked the mark and then did the closing and opening Floorp and then got the notification "Update failed. Restarting your browser may solve this problem." Then I went to folder to check properties attributes and it was to set to read only again. So I went to security tabs and gave permission to modify and write to all group/users AND an unknown user was there too. But I gave it permissions regardless just for the heck of it. Then, I did the close and open Floorp and this time it updated! After update I checked the core folder's property and it's again set to read only mode and the unknown user isn't there anymore and write/modify permission is gone from Users (Desktop name\Users) again. I don't know if I should be worried about that unknown user but I got the automatic update done. Any insight to what that might be or how to make it work without this hassle next time?

**Comment by uugaabuugaa** [comment] 2024-11-01 14:00
> Perhaps write access need not be explicitly given.

Sorry did you mean need to* be explicitly given? Cause I think modifying writing permission is the thing that worked. 
Edit: Which changed back to unpermitted state after the update.

**Comment by typeling1578** [comment] 2024-11-01 14:11
Hmmm, normally files are not written as read-only so there is no need to manually grant permissions, but for some reason it seems to be happening.
I will start another Issue on this.

**Comment by uugaabuugaa** [comment] 2024-11-01 14:15
Okay cool. I'll see if the same thing happens again for the next update.

**Comment by da3dsoul1** [comment] 2025-02-06 10:50
Um, somehow this bug happened again in floorp 11.23.0. When launching it updates itself to older version 11.22.0

**Comment by uugaabuugaa** [comment] 2025-02-06 17:45
> Um, somehow this bug happened again in floorp 11.23.0. When launching it updates itself to older version 11.22.0

The issue is still there. But there's an easy solution. Everytime you know there's an update to be installed the next time you open Floorp run it with admin privilege and the update should apply instantly.
